/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QTextEdit *textEdit_serial;
    QPushButton *connect_pushButton;
    QLabel *label_send_cnt;
    QLabel *label_recieve_cnt;
    QPushButton *pushButton_sned_test;
    QGroupBox *groupBox_6;
    QPushButton *Brake_pushButton;
    QPushButton *Magnet_1_pushButton;
    QPushButton *Magnet_2_pushButton;
    QWidget *tab_2;
    QGroupBox *groupBox;
    QLabel *label;
    QLineEdit *lineEdit_X;
    QLineEdit *lineEdit_dX;
    QLabel *label_2;
    QGroupBox *groupBox_2;
    QLabel *label_3;
    QLineEdit *lineEdit_theta;
    QLineEdit *lineEdit_dtheta;
    QLabel *label_4;
    QPushButton *show_data_analysis_pushButton;
    QLineEdit *lineEdit_test;
    QLabel *label_9;
    QPushButton *test_pushButton;
    QGroupBox *groupBox_3;
    QLabel *camer_label;
    QPushButton *camera_pushButton;
    QPushButton *save_image_pushButton;
    QLabel *camera_trigger_cnt_label;
    QLabel *camera_read_cnt_label;
    QLineEdit *sample_frequence_lineEdit;
    QLabel *label_35;
    QGroupBox *groupBox_8;
    QPushButton *remote_switch_pushButton;
    QPushButton *reset_position_pushButton;
    QGroupBox *groupBox_9;
    QLabel *label_15;
    QLineEdit *lineEdit_roll;
    QLineEdit *lineEdit_pitch;
    QLabel *label_16;
    QLabel *label_17;
    QLineEdit *lineEdit_yaw;
    QGroupBox *groupBox_11;
    QLabel *label_24;
    QLineEdit *lineEdit_l;
    QWidget *tab_3;
    QGroupBox *Mode_choose_groupBox;
    QRadioButton *Position_mode_radioButton;
    QRadioButton *Velocity_mode_radioButton;
    QRadioButton *Current_mode_radioButton;
    QGroupBox *groupBox_4;
    QPushButton *Position_send_pushButton;
    QLabel *label_5;
    QLineEdit *Position_expect_lineEdit;
    QLabel *label_6;
    QLineEdit *Velocity_expect_lineEdit;
    QPushButton *Velocity_send_pushButton;
    QLineEdit *Current_expect_lineEdit;
    QLabel *label_7;
    QPushButton *Current_send_pushButton;
    QPushButton *Limit_Velocity_send_pushButton;
    QLineEdit *Limit_velocity_lineEdit;
    QPushButton *Stop_pushButton;
    QGroupBox *groupBox_5;
    QRadioButton *Motor1_radioButton;
    QRadioButton *Motor2_radioButton;
    QPushButton *Zero_pushButton;
    QLabel *label_8;
    QGroupBox *Mode_choose_groupBox_2;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLineEdit *Driver_Velocity_Ki_lineEdit;
    QLineEdit *Driver_Velocity_Kp_lineEdit;
    QLineEdit *Driver_Velocity_Kd_lineEdit;
    QPushButton *Driver_Velocity_PID_Set_pushButton;
    QWidget *tab_4;
    QGroupBox *groupBox_7;
    QRadioButton *p_planner_radioButton;
    QRadioButton *step_planner_radioButton;
    QRadioButton *nankai_planner_radioButton;
    QGroupBox *groupBox_10;
    QPushButton *SC_send_pushButton;
    QLineEdit *SC_Xd_lineEdit;
    QLabel *label_21;
    QLabel *label_22;
    QLineEdit *SC_Td_lineEdit;
    QLabel *label_23;
    QLineEdit *SC_Ld_lineEdit;
    QLineEdit *Ki_lineEdit;
    QLineEdit *Kd_lineEdit;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *Kp_lineEdit;
    QLabel *label_10;
    QLineEdit *floor_height_lineEdit;
    QCheckBox *drop_flag_checkBox;
    QLabel *label_37;
    QGroupBox *groupBox_12;
    QLineEdit *delta_T_lineEdit;
    QLabel *label_25;
    QRadioButton *ZV_radioButton;
    QRadioButton *ZVDD_radioButton;
    QRadioButton *ZVD_radioButton;
    QRadioButton *NoZV_radioButton;
    QGroupBox *groupBox_13;
    QLineEdit *sample_name_lineEdit;
    QLabel *label_26;
    QCheckBox *auto_sample_checkBox;
    QPushButton *sample_save_pushButton;
    QCheckBox *state_label_checkBox;
    QCheckBox *image_label_checkBox;
    QGroupBox *groupBox_14;
    QPushButton *Vx_send_pushButton;
    QLineEdit *Vx_lineEdit;
    QLabel *label_36;
    QLabel *label_38;
    QLineEdit *Vx_t_lineEdit;
    QWidget *tab_5;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLineEdit *M_lineEdit;
    QLineEdit *m_lineEdit;
    QLineEdit *v_max_lineEdit;
    QLineEdit *a_max_lineEdit;
    QLineEdit *m_lineEdit_;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(675, 591);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(20, 10, 641, 541));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        textEdit_serial = new QTextEdit(tab);
        textEdit_serial->setObjectName(QStringLiteral("textEdit_serial"));
        textEdit_serial->setGeometry(QRect(30, 40, 231, 171));
        connect_pushButton = new QPushButton(tab);
        connect_pushButton->setObjectName(QStringLiteral("connect_pushButton"));
        connect_pushButton->setGeometry(QRect(280, 40, 99, 27));
        label_send_cnt = new QLabel(tab);
        label_send_cnt->setObjectName(QStringLiteral("label_send_cnt"));
        label_send_cnt->setGeometry(QRect(10, 390, 91, 17));
        label_recieve_cnt = new QLabel(tab);
        label_recieve_cnt->setObjectName(QStringLiteral("label_recieve_cnt"));
        label_recieve_cnt->setGeometry(QRect(110, 390, 81, 17));
        pushButton_sned_test = new QPushButton(tab);
        pushButton_sned_test->setObjectName(QStringLiteral("pushButton_sned_test"));
        pushButton_sned_test->setGeometry(QRect(210, 380, 99, 27));
        groupBox_6 = new QGroupBox(tab);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(480, 250, 141, 121));
        Brake_pushButton = new QPushButton(groupBox_6);
        Brake_pushButton->setObjectName(QStringLiteral("Brake_pushButton"));
        Brake_pushButton->setGeometry(QRect(10, 30, 121, 27));
        Magnet_1_pushButton = new QPushButton(groupBox_6);
        Magnet_1_pushButton->setObjectName(QStringLiteral("Magnet_1_pushButton"));
        Magnet_1_pushButton->setGeometry(QRect(10, 60, 121, 27));
        Magnet_2_pushButton = new QPushButton(groupBox_6);
        Magnet_2_pushButton->setObjectName(QStringLiteral("Magnet_2_pushButton"));
        Magnet_2_pushButton->setGeometry(QRect(10, 90, 121, 27));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        groupBox = new QGroupBox(tab_2);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 10, 191, 61));
        label = new QLabel(groupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 30, 21, 21));
        lineEdit_X = new QLineEdit(groupBox);
        lineEdit_X->setObjectName(QStringLiteral("lineEdit_X"));
        lineEdit_X->setGeometry(QRect(20, 30, 71, 27));
        lineEdit_dX = new QLineEdit(groupBox);
        lineEdit_dX->setObjectName(QStringLiteral("lineEdit_dX"));
        lineEdit_dX->setGeometry(QRect(120, 30, 61, 27));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(100, 30, 21, 21));
        groupBox_2 = new QGroupBox(tab_2);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(230, 10, 241, 61));
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 30, 51, 21));
        lineEdit_theta = new QLineEdit(groupBox_2);
        lineEdit_theta->setObjectName(QStringLiteral("lineEdit_theta"));
        lineEdit_theta->setGeometry(QRect(50, 30, 61, 27));
        lineEdit_dtheta = new QLineEdit(groupBox_2);
        lineEdit_dtheta->setObjectName(QStringLiteral("lineEdit_dtheta"));
        lineEdit_dtheta->setGeometry(QRect(170, 30, 61, 27));
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(120, 30, 51, 21));
        show_data_analysis_pushButton = new QPushButton(tab_2);
        show_data_analysis_pushButton->setObjectName(QStringLiteral("show_data_analysis_pushButton"));
        show_data_analysis_pushButton->setGeometry(QRect(500, 130, 91, 27));
        lineEdit_test = new QLineEdit(tab_2);
        lineEdit_test->setObjectName(QStringLiteral("lineEdit_test"));
        lineEdit_test->setGeometry(QRect(510, 320, 113, 27));
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(510, 300, 31, 21));
        test_pushButton = new QPushButton(tab_2);
        test_pushButton->setObjectName(QStringLiteral("test_pushButton"));
        test_pushButton->setGeometry(QRect(510, 350, 99, 27));
        groupBox_3 = new QGroupBox(tab_2);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 190, 461, 311));
        camer_label = new QLabel(groupBox_3);
        camer_label->setObjectName(QStringLiteral("camer_label"));
        camer_label->setGeometry(QRect(10, 50, 306, 256));
        camera_pushButton = new QPushButton(groupBox_3);
        camera_pushButton->setObjectName(QStringLiteral("camera_pushButton"));
        camera_pushButton->setGeometry(QRect(340, 120, 99, 27));
        save_image_pushButton = new QPushButton(groupBox_3);
        save_image_pushButton->setObjectName(QStringLiteral("save_image_pushButton"));
        save_image_pushButton->setGeometry(QRect(340, 160, 99, 27));
        camera_trigger_cnt_label = new QLabel(groupBox_3);
        camera_trigger_cnt_label->setObjectName(QStringLiteral("camera_trigger_cnt_label"));
        camera_trigger_cnt_label->setGeometry(QRect(340, 240, 131, 17));
        camera_read_cnt_label = new QLabel(groupBox_3);
        camera_read_cnt_label->setObjectName(QStringLiteral("camera_read_cnt_label"));
        camera_read_cnt_label->setGeometry(QRect(340, 270, 131, 17));
        sample_frequence_lineEdit = new QLineEdit(groupBox_3);
        sample_frequence_lineEdit->setObjectName(QStringLiteral("sample_frequence_lineEdit"));
        sample_frequence_lineEdit->setGeometry(QRect(350, 80, 61, 27));
        label_35 = new QLabel(groupBox_3);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(350, 50, 101, 20));
        groupBox_8 = new QGroupBox(tab_2);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(500, 190, 120, 80));
        remote_switch_pushButton = new QPushButton(groupBox_8);
        remote_switch_pushButton->setObjectName(QStringLiteral("remote_switch_pushButton"));
        remote_switch_pushButton->setGeometry(QRect(10, 30, 99, 27));
        reset_position_pushButton = new QPushButton(tab_2);
        reset_position_pushButton->setObjectName(QStringLiteral("reset_position_pushButton"));
        reset_position_pushButton->setGeometry(QRect(500, 90, 101, 27));
        groupBox_9 = new QGroupBox(tab_2);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(10, 90, 431, 61));
        label_15 = new QLabel(groupBox_9);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 30, 31, 21));
        lineEdit_roll = new QLineEdit(groupBox_9);
        lineEdit_roll->setObjectName(QStringLiteral("lineEdit_roll"));
        lineEdit_roll->setGeometry(QRect(40, 30, 91, 27));
        lineEdit_pitch = new QLineEdit(groupBox_9);
        lineEdit_pitch->setObjectName(QStringLiteral("lineEdit_pitch"));
        lineEdit_pitch->setGeometry(QRect(180, 30, 91, 27));
        label_16 = new QLabel(groupBox_9);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(140, 30, 41, 21));
        label_17 = new QLabel(groupBox_9);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(290, 30, 31, 21));
        lineEdit_yaw = new QLineEdit(groupBox_9);
        lineEdit_yaw->setObjectName(QStringLiteral("lineEdit_yaw"));
        lineEdit_yaw->setGeometry(QRect(320, 30, 91, 27));
        groupBox_11 = new QGroupBox(tab_2);
        groupBox_11->setObjectName(QStringLiteral("groupBox_11"));
        groupBox_11->setGeometry(QRect(500, 10, 91, 61));
        label_24 = new QLabel(groupBox_11);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(10, 30, 16, 21));
        lineEdit_l = new QLineEdit(groupBox_11);
        lineEdit_l->setObjectName(QStringLiteral("lineEdit_l"));
        lineEdit_l->setGeometry(QRect(20, 30, 61, 27));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        Mode_choose_groupBox = new QGroupBox(tab_3);
        Mode_choose_groupBox->setObjectName(QStringLiteral("Mode_choose_groupBox"));
        Mode_choose_groupBox->setGeometry(QRect(20, 20, 401, 71));
        Position_mode_radioButton = new QRadioButton(Mode_choose_groupBox);
        Position_mode_radioButton->setObjectName(QStringLiteral("Position_mode_radioButton"));
        Position_mode_radioButton->setGeometry(QRect(10, 30, 131, 22));
        Velocity_mode_radioButton = new QRadioButton(Mode_choose_groupBox);
        Velocity_mode_radioButton->setObjectName(QStringLiteral("Velocity_mode_radioButton"));
        Velocity_mode_radioButton->setGeometry(QRect(140, 30, 131, 22));
        Current_mode_radioButton = new QRadioButton(Mode_choose_groupBox);
        Current_mode_radioButton->setObjectName(QStringLiteral("Current_mode_radioButton"));
        Current_mode_radioButton->setGeometry(QRect(270, 30, 131, 21));
        groupBox_4 = new QGroupBox(tab_3);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(20, 100, 411, 231));
        Position_send_pushButton = new QPushButton(groupBox_4);
        Position_send_pushButton->setObjectName(QStringLiteral("Position_send_pushButton"));
        Position_send_pushButton->setGeometry(QRect(270, 40, 81, 27));
        label_5 = new QLabel(groupBox_4);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 36, 91, 31));
        Position_expect_lineEdit = new QLineEdit(groupBox_4);
        Position_expect_lineEdit->setObjectName(QStringLiteral("Position_expect_lineEdit"));
        Position_expect_lineEdit->setGeometry(QRect(140, 40, 113, 27));
        label_6 = new QLabel(groupBox_4);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 86, 101, 31));
        Velocity_expect_lineEdit = new QLineEdit(groupBox_4);
        Velocity_expect_lineEdit->setObjectName(QStringLiteral("Velocity_expect_lineEdit"));
        Velocity_expect_lineEdit->setGeometry(QRect(140, 90, 113, 27));
        Velocity_send_pushButton = new QPushButton(groupBox_4);
        Velocity_send_pushButton->setObjectName(QStringLiteral("Velocity_send_pushButton"));
        Velocity_send_pushButton->setGeometry(QRect(270, 90, 81, 27));
        Current_expect_lineEdit = new QLineEdit(groupBox_4);
        Current_expect_lineEdit->setObjectName(QStringLiteral("Current_expect_lineEdit"));
        Current_expect_lineEdit->setGeometry(QRect(140, 140, 113, 27));
        label_7 = new QLabel(groupBox_4);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(30, 136, 91, 31));
        Current_send_pushButton = new QPushButton(groupBox_4);
        Current_send_pushButton->setObjectName(QStringLiteral("Current_send_pushButton"));
        Current_send_pushButton->setGeometry(QRect(270, 140, 81, 27));
        Limit_Velocity_send_pushButton = new QPushButton(groupBox_4);
        Limit_Velocity_send_pushButton->setObjectName(QStringLiteral("Limit_Velocity_send_pushButton"));
        Limit_Velocity_send_pushButton->setGeometry(QRect(270, 190, 81, 27));
        Limit_velocity_lineEdit = new QLineEdit(groupBox_4);
        Limit_velocity_lineEdit->setObjectName(QStringLiteral("Limit_velocity_lineEdit"));
        Limit_velocity_lineEdit->setGeometry(QRect(140, 190, 113, 27));
        Stop_pushButton = new QPushButton(tab_3);
        Stop_pushButton->setObjectName(QStringLiteral("Stop_pushButton"));
        Stop_pushButton->setGeometry(QRect(450, 150, 101, 61));
        groupBox_5 = new QGroupBox(tab_3);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(450, 20, 120, 71));
        Motor1_radioButton = new QRadioButton(groupBox_5);
        Motor1_radioButton->setObjectName(QStringLiteral("Motor1_radioButton"));
        Motor1_radioButton->setGeometry(QRect(10, 20, 117, 22));
        Motor2_radioButton = new QRadioButton(groupBox_5);
        Motor2_radioButton->setObjectName(QStringLiteral("Motor2_radioButton"));
        Motor2_radioButton->setGeometry(QRect(10, 50, 117, 22));
        Zero_pushButton = new QPushButton(tab_3);
        Zero_pushButton->setObjectName(QStringLiteral("Zero_pushButton"));
        Zero_pushButton->setGeometry(QRect(450, 230, 101, 61));
        label_8 = new QLabel(tab_3);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(30, 280, 141, 41));
        Mode_choose_groupBox_2 = new QGroupBox(tab_3);
        Mode_choose_groupBox_2->setObjectName(QStringLiteral("Mode_choose_groupBox_2"));
        Mode_choose_groupBox_2->setGeometry(QRect(20, 350, 451, 71));
        label_39 = new QLabel(Mode_choose_groupBox_2);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(150, 30, 21, 17));
        label_40 = new QLabel(Mode_choose_groupBox_2);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(260, 30, 21, 17));
        label_41 = new QLabel(Mode_choose_groupBox_2);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(20, 30, 21, 17));
        Driver_Velocity_Ki_lineEdit = new QLineEdit(Mode_choose_groupBox_2);
        Driver_Velocity_Ki_lineEdit->setObjectName(QStringLiteral("Driver_Velocity_Ki_lineEdit"));
        Driver_Velocity_Ki_lineEdit->setGeometry(QRect(170, 30, 61, 27));
        Driver_Velocity_Kp_lineEdit = new QLineEdit(Mode_choose_groupBox_2);
        Driver_Velocity_Kp_lineEdit->setObjectName(QStringLiteral("Driver_Velocity_Kp_lineEdit"));
        Driver_Velocity_Kp_lineEdit->setGeometry(QRect(40, 30, 61, 27));
        Driver_Velocity_Kd_lineEdit = new QLineEdit(Mode_choose_groupBox_2);
        Driver_Velocity_Kd_lineEdit->setObjectName(QStringLiteral("Driver_Velocity_Kd_lineEdit"));
        Driver_Velocity_Kd_lineEdit->setGeometry(QRect(280, 30, 61, 27));
        Driver_Velocity_PID_Set_pushButton = new QPushButton(Mode_choose_groupBox_2);
        Driver_Velocity_PID_Set_pushButton->setObjectName(QStringLiteral("Driver_Velocity_PID_Set_pushButton"));
        Driver_Velocity_PID_Set_pushButton->setGeometry(QRect(360, 30, 81, 27));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        groupBox_7 = new QGroupBox(tab_4);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(20, 10, 571, 71));
        p_planner_radioButton = new QRadioButton(groupBox_7);
        p_planner_radioButton->setObjectName(QStringLiteral("p_planner_radioButton"));
        p_planner_radioButton->setGeometry(QRect(10, 30, 117, 22));
        step_planner_radioButton = new QRadioButton(groupBox_7);
        step_planner_radioButton->setObjectName(QStringLiteral("step_planner_radioButton"));
        step_planner_radioButton->setGeometry(QRect(110, 30, 117, 22));
        nankai_planner_radioButton = new QRadioButton(groupBox_7);
        nankai_planner_radioButton->setObjectName(QStringLiteral("nankai_planner_radioButton"));
        nankai_planner_radioButton->setGeometry(QRect(230, 30, 141, 22));
        groupBox_10 = new QGroupBox(tab_4);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setGeometry(QRect(20, 90, 381, 131));
        SC_send_pushButton = new QPushButton(groupBox_10);
        SC_send_pushButton->setObjectName(QStringLiteral("SC_send_pushButton"));
        SC_send_pushButton->setGeometry(QRect(298, 90, 71, 31));
        SC_Xd_lineEdit = new QLineEdit(groupBox_10);
        SC_Xd_lineEdit->setObjectName(QStringLiteral("SC_Xd_lineEdit"));
        SC_Xd_lineEdit->setGeometry(QRect(60, 60, 61, 27));
        label_21 = new QLabel(groupBox_10);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 60, 51, 20));
        label_22 = new QLabel(groupBox_10);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(270, 60, 31, 20));
        SC_Td_lineEdit = new QLineEdit(groupBox_10);
        SC_Td_lineEdit->setObjectName(QStringLiteral("SC_Td_lineEdit"));
        SC_Td_lineEdit->setGeometry(QRect(300, 60, 61, 27));
        label_23 = new QLabel(groupBox_10);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(140, 60, 51, 20));
        SC_Ld_lineEdit = new QLineEdit(groupBox_10);
        SC_Ld_lineEdit->setObjectName(QStringLiteral("SC_Ld_lineEdit"));
        SC_Ld_lineEdit->setGeometry(QRect(190, 60, 61, 27));
        Ki_lineEdit = new QLineEdit(groupBox_10);
        Ki_lineEdit->setObjectName(QStringLiteral("Ki_lineEdit"));
        Ki_lineEdit->setGeometry(QRect(190, 30, 61, 27));
        Kd_lineEdit = new QLineEdit(groupBox_10);
        Kd_lineEdit->setObjectName(QStringLiteral("Kd_lineEdit"));
        Kd_lineEdit->setGeometry(QRect(300, 30, 61, 27));
        label_11 = new QLabel(groupBox_10);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(170, 30, 21, 17));
        label_12 = new QLabel(groupBox_10);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(280, 30, 21, 17));
        Kp_lineEdit = new QLineEdit(groupBox_10);
        Kp_lineEdit->setObjectName(QStringLiteral("Kp_lineEdit"));
        Kp_lineEdit->setGeometry(QRect(60, 30, 61, 27));
        label_10 = new QLabel(groupBox_10);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(40, 30, 21, 17));
        floor_height_lineEdit = new QLineEdit(groupBox_10);
        floor_height_lineEdit->setObjectName(QStringLiteral("floor_height_lineEdit"));
        floor_height_lineEdit->setGeometry(QRect(60, 100, 61, 27));
        drop_flag_checkBox = new QCheckBox(groupBox_10);
        drop_flag_checkBox->setObjectName(QStringLiteral("drop_flag_checkBox"));
        drop_flag_checkBox->setGeometry(QRect(170, 100, 101, 22));
        label_37 = new QLabel(groupBox_10);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(20, 100, 41, 20));
        groupBox_12 = new QGroupBox(tab_4);
        groupBox_12->setObjectName(QStringLiteral("groupBox_12"));
        groupBox_12->setGeometry(QRect(440, 90, 151, 161));
        delta_T_lineEdit = new QLineEdit(groupBox_12);
        delta_T_lineEdit->setObjectName(QStringLiteral("delta_T_lineEdit"));
        delta_T_lineEdit->setGeometry(QRect(80, 120, 61, 27));
        label_25 = new QLabel(groupBox_12);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(10, 120, 71, 20));
        ZV_radioButton = new QRadioButton(groupBox_12);
        ZV_radioButton->setObjectName(QStringLiteral("ZV_radioButton"));
        ZV_radioButton->setGeometry(QRect(10, 50, 61, 22));
        ZVDD_radioButton = new QRadioButton(groupBox_12);
        ZVDD_radioButton->setObjectName(QStringLiteral("ZVDD_radioButton"));
        ZVDD_radioButton->setGeometry(QRect(10, 90, 81, 22));
        ZVD_radioButton = new QRadioButton(groupBox_12);
        ZVD_radioButton->setObjectName(QStringLiteral("ZVD_radioButton"));
        ZVD_radioButton->setGeometry(QRect(10, 70, 61, 22));
        NoZV_radioButton = new QRadioButton(groupBox_12);
        NoZV_radioButton->setObjectName(QStringLiteral("NoZV_radioButton"));
        NoZV_radioButton->setGeometry(QRect(10, 30, 71, 22));
        groupBox_13 = new QGroupBox(tab_4);
        groupBox_13->setObjectName(QStringLiteral("groupBox_13"));
        groupBox_13->setGeometry(QRect(450, 270, 131, 221));
        sample_name_lineEdit = new QLineEdit(groupBox_13);
        sample_name_lineEdit->setObjectName(QStringLiteral("sample_name_lineEdit"));
        sample_name_lineEdit->setGeometry(QRect(10, 50, 101, 27));
        label_26 = new QLabel(groupBox_13);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(10, 30, 51, 20));
        auto_sample_checkBox = new QCheckBox(groupBox_13);
        auto_sample_checkBox->setObjectName(QStringLiteral("auto_sample_checkBox"));
        auto_sample_checkBox->setGeometry(QRect(10, 150, 101, 22));
        sample_save_pushButton = new QPushButton(groupBox_13);
        sample_save_pushButton->setObjectName(QStringLiteral("sample_save_pushButton"));
        sample_save_pushButton->setGeometry(QRect(10, 180, 61, 31));
        state_label_checkBox = new QCheckBox(groupBox_13);
        state_label_checkBox->setObjectName(QStringLiteral("state_label_checkBox"));
        state_label_checkBox->setGeometry(QRect(10, 120, 101, 22));
        image_label_checkBox = new QCheckBox(groupBox_13);
        image_label_checkBox->setObjectName(QStringLiteral("image_label_checkBox"));
        image_label_checkBox->setGeometry(QRect(10, 90, 101, 22));
        groupBox_14 = new QGroupBox(tab_4);
        groupBox_14->setObjectName(QStringLiteral("groupBox_14"));
        groupBox_14->setGeometry(QRect(20, 250, 381, 81));
        Vx_send_pushButton = new QPushButton(groupBox_14);
        Vx_send_pushButton->setObjectName(QStringLiteral("Vx_send_pushButton"));
        Vx_send_pushButton->setGeometry(QRect(298, 40, 71, 31));
        Vx_lineEdit = new QLineEdit(groupBox_14);
        Vx_lineEdit->setObjectName(QStringLiteral("Vx_lineEdit"));
        Vx_lineEdit->setGeometry(QRect(80, 40, 61, 27));
        label_36 = new QLabel(groupBox_14);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 40, 71, 20));
        label_38 = new QLabel(groupBox_14);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(165, 40, 21, 20));
        Vx_t_lineEdit = new QLineEdit(groupBox_14);
        Vx_t_lineEdit->setObjectName(QStringLiteral("Vx_t_lineEdit"));
        Vx_t_lineEdit->setGeometry(QRect(190, 40, 61, 27));
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        label_13 = new QLabel(tab_5);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(30, 90, 51, 17));
        label_14 = new QLabel(tab_5);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(30, 120, 51, 17));
        label_27 = new QLabel(tab_5);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(60, 150, 16, 17));
        label_28 = new QLabel(tab_5);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(60, 30, 21, 17));
        label_29 = new QLabel(tab_5);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(60, 60, 21, 17));
        M_lineEdit = new QLineEdit(tab_5);
        M_lineEdit->setObjectName(QStringLiteral("M_lineEdit"));
        M_lineEdit->setGeometry(QRect(80, 30, 81, 27));
        m_lineEdit = new QLineEdit(tab_5);
        m_lineEdit->setObjectName(QStringLiteral("m_lineEdit"));
        m_lineEdit->setGeometry(QRect(80, 60, 81, 27));
        v_max_lineEdit = new QLineEdit(tab_5);
        v_max_lineEdit->setObjectName(QStringLiteral("v_max_lineEdit"));
        v_max_lineEdit->setGeometry(QRect(80, 90, 81, 27));
        a_max_lineEdit = new QLineEdit(tab_5);
        a_max_lineEdit->setObjectName(QStringLiteral("a_max_lineEdit"));
        a_max_lineEdit->setGeometry(QRect(80, 120, 81, 27));
        m_lineEdit_ = new QLineEdit(tab_5);
        m_lineEdit_->setObjectName(QStringLiteral("m_lineEdit_"));
        m_lineEdit_->setGeometry(QRect(80, 150, 81, 27));
        label_30 = new QLabel(tab_5);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(170, 30, 41, 21));
        label_31 = new QLabel(tab_5);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(170, 60, 41, 21));
        label_32 = new QLabel(tab_5);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(170, 90, 41, 21));
        label_33 = new QLabel(tab_5);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(170, 120, 51, 21));
        label_34 = new QLabel(tab_5);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(170, 150, 51, 21));
        tabWidget->addTab(tab_5, QString());
        MainWindow->setCentralWidget(centralWidget);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(3);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        connect_pushButton->setText(QApplication::translate("MainWindow", "connect", 0));
        label_send_cnt->setText(QApplication::translate("MainWindow", "S:", 0));
        label_recieve_cnt->setText(QApplication::translate("MainWindow", "R:", 0));
        pushButton_sned_test->setText(QApplication::translate("MainWindow", "send test", 0));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "relay control", 0));
        Brake_pushButton->setText(QApplication::translate("MainWindow", "Brake on", 0));
        Magnet_1_pushButton->setText(QApplication::translate("MainWindow", "Magnet_1 on", 0));
        Magnet_2_pushButton->setText(QApplication::translate("MainWindow", "Magnet_2 on", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Main", 0));
        groupBox->setTitle(QApplication::translate("MainWindow", "X position and velocity", 0));
        label->setText(QApplication::translate("MainWindow", "X", 0));
        label_2->setText(QApplication::translate("MainWindow", "dX", 0));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Theta position and velocity", 0));
        label_3->setText(QApplication::translate("MainWindow", "Theta", 0));
        label_4->setText(QApplication::translate("MainWindow", "dtheta", 0));
        show_data_analysis_pushButton->setText(QApplication::translate("MainWindow", "show curve", 0));
        label_9->setText(QApplication::translate("MainWindow", "test", 0));
        test_pushButton->setText(QApplication::translate("MainWindow", "test_send", 0));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "Camera image", 0));
        camer_label->setText(QApplication::translate("MainWindow", "no image!", 0));
        camera_pushButton->setText(QApplication::translate("MainWindow", "open camera", 0));
        save_image_pushButton->setText(QApplication::translate("MainWindow", "save image", 0));
        camera_trigger_cnt_label->setText(QApplication::translate("MainWindow", "trigger cnt:", 0));
        camera_read_cnt_label->setText(QApplication::translate("MainWindow", "read cnt:", 0));
        label_35->setText(QApplication::translate("MainWindow", "frequence(Hz)", 0));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "remote switch", 0));
        remote_switch_pushButton->setText(QApplication::translate("MainWindow", "remote on", 0));
        reset_position_pushButton->setText(QApplication::translate("MainWindow", "reset position", 0));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "IMU", 0));
        label_15->setText(QApplication::translate("MainWindow", "roll", 0));
        label_16->setText(QApplication::translate("MainWindow", "pitch", 0));
        label_17->setText(QApplication::translate("MainWindow", "yaw", 0));
        groupBox_11->setTitle(QApplication::translate("MainWindow", "l length", 0));
        label_24->setText(QApplication::translate("MainWindow", "l", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Sensor Data", 0));
        Mode_choose_groupBox->setTitle(QApplication::translate("MainWindow", "Mode choose", 0));
        Position_mode_radioButton->setText(QApplication::translate("MainWindow", "Position Mode", 0));
        Velocity_mode_radioButton->setText(QApplication::translate("MainWindow", "Velocity Mode", 0));
        Current_mode_radioButton->setText(QApplication::translate("MainWindow", "Current Mode", 0));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "send value", 0));
        Position_send_pushButton->setText(QApplication::translate("MainWindow", "send", 0));
        label_5->setText(QApplication::translate("MainWindow", "Position(deg)", 0));
        label_6->setText(QApplication::translate("MainWindow", "Velocity(rpm)", 0));
        Velocity_send_pushButton->setText(QApplication::translate("MainWindow", "send", 0));
        label_7->setText(QApplication::translate("MainWindow", "Current(mA)", 0));
        Current_send_pushButton->setText(QApplication::translate("MainWindow", "send", 0));
        Limit_Velocity_send_pushButton->setText(QApplication::translate("MainWindow", "send", 0));
        Stop_pushButton->setText(QApplication::translate("MainWindow", "STOP", 0));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "Motor choose", 0));
        Motor1_radioButton->setText(QApplication::translate("MainWindow", "Motor1", 0));
        Motor2_radioButton->setText(QApplication::translate("MainWindow", "Motor2", 0));
        Zero_pushButton->setText(QApplication::translate("MainWindow", "ZERO", 0));
        label_8->setText(QApplication::translate("MainWindow", "Max velocity(rpm)", 0));
        Mode_choose_groupBox_2->setTitle(QApplication::translate("MainWindow", "Motor Velocity PID Set", 0));
        label_39->setText(QApplication::translate("MainWindow", "Ki", 0));
        label_40->setText(QApplication::translate("MainWindow", "Kd", 0));
        label_41->setText(QApplication::translate("MainWindow", "Kp", 0));
        Driver_Velocity_Ki_lineEdit->setText(QString());
        Driver_Velocity_PID_Set_pushButton->setText(QApplication::translate("MainWindow", "set", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Motor Control", 0));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "planner choose", 0));
        p_planner_radioButton->setText(QApplication::translate("MainWindow", "p planner", 0));
        step_planner_radioButton->setText(QApplication::translate("MainWindow", "step planner", 0));
        nankai_planner_radioButton->setText(QApplication::translate("MainWindow", "nankai planner", 0));
        groupBox_10->setTitle(QApplication::translate("MainWindow", "position experiment", 0));
        SC_send_pushButton->setText(QApplication::translate("MainWindow", "start", 0));
        label_21->setText(QApplication::translate("MainWindow", "Xd/mm", 0));
        label_22->setText(QApplication::translate("MainWindow", "Td/s", 0));
        label_23->setText(QApplication::translate("MainWindow", "Ld/mm", 0));
        Ki_lineEdit->setText(QString());
        label_11->setText(QApplication::translate("MainWindow", "Ki", 0));
        label_12->setText(QApplication::translate("MainWindow", "Kd", 0));
        label_10->setText(QApplication::translate("MainWindow", "Kp", 0));
        drop_flag_checkBox->setText(QApplication::translate("MainWindow", "drop flag", 0));
        label_37->setText(QApplication::translate("MainWindow", "floor", 0));
        groupBox_12->setTitle(QApplication::translate("MainWindow", "ZV set", 0));
        label_25->setText(QApplication::translate("MainWindow", "delat_T(s)", 0));
        ZV_radioButton->setText(QApplication::translate("MainWindow", "ZV", 0));
        ZVDD_radioButton->setText(QApplication::translate("MainWindow", "ZVDD", 0));
        ZVD_radioButton->setText(QApplication::translate("MainWindow", "ZVD", 0));
        NoZV_radioButton->setText(QApplication::translate("MainWindow", "NULL", 0));
        groupBox_13->setTitle(QApplication::translate("MainWindow", "sampling", 0));
        label_26->setText(QApplication::translate("MainWindow", "folder", 0));
        auto_sample_checkBox->setText(QApplication::translate("MainWindow", "auto save", 0));
        sample_save_pushButton->setText(QApplication::translate("MainWindow", "sample", 0));
        state_label_checkBox->setText(QApplication::translate("MainWindow", "state", 0));
        image_label_checkBox->setText(QApplication::translate("MainWindow", "image", 0));
        groupBox_14->setTitle(QApplication::translate("MainWindow", "velocity experiment", 0));
        Vx_send_pushButton->setText(QApplication::translate("MainWindow", "start", 0));
        label_36->setText(QApplication::translate("MainWindow", "Vx(mm/s)", 0));
        label_38->setText(QApplication::translate("MainWindow", "t/s", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Experiments", 0));
        label_13->setText(QApplication::translate("MainWindow", "v_max", 0));
        label_14->setText(QApplication::translate("MainWindow", "a_max", 0));
        label_27->setText(QApplication::translate("MainWindow", "l", 0));
        label_28->setText(QApplication::translate("MainWindow", "M", 0));
        label_29->setText(QApplication::translate("MainWindow", "m", 0));
        label_30->setText(QApplication::translate("MainWindow", "kg", 0));
        label_31->setText(QApplication::translate("MainWindow", "kg", 0));
        label_32->setText(QApplication::translate("MainWindow", "m/s", 0));
        label_33->setText(QApplication::translate("MainWindow", "m^2/s", 0));
        label_34->setText(QApplication::translate("MainWindow", "m", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("MainWindow", "basic para", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
